### ISSUE TITLE
Dodaj wiki do repozytorium

### ISSUE THREAD

**Issue by MarcinMichalik** [mistermiki/Ultimate-2021-Frontend-Dev#1]

**Comment by mistermiki** [comment]
Haha, to nie jest takie oczywiste XD Popracuję nad tym i zamknę ten issue.

**Comment by mistermiki** [comment]
Musiałem zmienić dostępność całego repozytorium z prywatnego na publiczne, żeby dodać wiki. W darmowej wersji nie można mieć wiki w prywatnym repo. This fixes #1.
